### ISSUE TITLE
image.bitdepth is overwritten when reading png when converting to nitro format

### ISSUE THREAD

**Issue by BluRosie** [red031000/nitrogfx#17]
https://github.com/red031000/nitrogfx/blob/7b048127ad49bcc0b07ed8e103a80d94963b96c6/main.c#L144-L146
https://github.com/red031000/nitrogfx/blob/7b048127ad49bcc0b07ed8e103a80d94963b96c6/main.c#L163-L165

this causes the `options->bitdepth` to not be taken into account at all because `image.bitdepth` is passed to `WriteNtrImage` and now my 8bpp mudkip doesn't convert properly after being run through aseprite :(

![85D5B49D-8153-4E7A-9FB0-5A7EAE4C6F92](https://github.com/user-attachments/assets/35d8eac0-a5e2-41e6-9840-daaa07192cda)

passing `options->bitdepth` instead fixes the problem and works as-is

**Comment by red031000** [comment]
you can make a PR if you wish, if not I can do it later on, this is a holdover from GBA code, which is why it is this way

**Comment by red031000** [comment]
fixed :)

**Comment by BluRosie** [comment]
tank yew
